// <auto-generated />
using ASP.NET_Core_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_Core_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211201084623_Added mileage to Car")]
    partial class AddedmileagetoCar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.NET_Core_Project.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volvo",
                            Mileage = 0,
                            Model = "V70",
                            RegNumber = "ABC-123"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "SAAB",
                            Mileage = 0,
                            Model = "93",
                            RegNumber = "DEF-456"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            Mileage = 0,
                            Model = "E38",
                            RegNumber = "GHI-789"
                        });
                });

            modelBuilder.Entity("ASP.NET_Core_Project.Models.OwnerModel", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            SSN = "1234567980",
                            Name = "Jonathan Krall"
                        },
                        new
                        {
                            SSN = "4564513221",
                            Name = "Anna Andersson"
                        },
                        new
                        {
                            SSN = "523423423",
                            Name = "Robin Robinsson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
